image: maven:3.5.4-jdk-8

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - analyze
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - mvn compile

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - mvn clean test

unit_test:
  stage: test
  script:
    - mvn clean test


analyze-job:
  stage: analyze
  script:
    - mvn verify sonar:sonar -Dsonar.qualitygate.wait=true

